name: Pipiline de produção
env: 
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}


on:
  push:
    branches: 
    - main

jobs:

  job1:
    name: CI - Buld e descrição do artefato
    runs-on: ubuntu-latest
    steps:
      - name: Pegar codigo de Repositorio
        uses: actions/checkout@v3

      - name: Instalando pacotes do npm
        run: npm install

      - name: Gerando a documentação do Swagger.json
        run: npm run autoDoc

      - name: Apagando pasta node_modules
        run: rm -rf node_modules

      - name: Apagando pasta .git
        run: rm -rf .git

      - name: Arquivos e pastas
        run: ls

      - name: Criando artefato ZIP do código buildado
        uses: actions/upload-artifact@v3
        with:
          name: artefato
          retention-days: 1
          path: ./



  job2:
    name: CD - deploy na vercel
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - name: Baixando artefato do código buildado
        uses: actions/download-artifact@v3
        with:
          name: artefato

      - name: Instalando pacotes do npm
        run: npm install

      - name: Arquivos e pastas do artefato
        run: ls

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: BUscando informações do anbiente na vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build de artefato do projeto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy do artefato do projeto na vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
